Repository Open-reSource/openresource.dev, pull requests merged in 2023-05, with the labels that each got.

#29 ci: update showcase
  src/data/showcase.json
Labels: ci

#31 ci: update showcase
  src/data/showcase.json
Labels: ci

#36 ci: update showcase
  src/data/showcase.json
Labels: ci

#43 ci: update showcase
  src/data/showcase.json
Labels: ci

#12 feat(a11y): improve focus visible rendering
  src/global.css
Labels: accessibility

#54 chore(deps): bump dependencies
  package-lock.json
  package.json
Labels: dependencies, chore

#55 ci: update showcase
  src/data/showcase.json
Labels: ci

#58 docs: new 'Can I Take This Issue?' article
  src/content/articles/can-i-take-this-issue.mdx
Labels: content

#60 feat: add progress scroll to articles and chapters
  src/components/ProgressScroll.astro
  src/layouts/Layout.astro
  src/pages/articles/[...slug].astro
  src/pages/guide/[...slug].astro
Labels: feature

#62 docs: update 'Can I Take This Issue?' article
  src/content/articles/can-i-take-this-issue.mdx
Labels: content

#66 feat(license): change licensing to CC BY-NC-SA 4.0 for articles and guide content
  CONTRIBUTING.md
  LICENSE
  README.md
  src/components/CreativeCommonMention.astro
  src/pages/articles/[...slug].astro
  src/pages/guide/[...slug].astro
Labels: feature

#68 docs(article): enhance 'Display your sponsors in your GitHub READMEs'
  src/content/articles/display-your-sponsors-in-your-github-readmes.mdx
Labels: content

#69 chore(deps): bump vercel from 29.0.3 to 29.3.6
  package-lock.json
  package.json
Labels: dependencies

#70 fix(content): uniformize capitalized titles in modules and chapters
  src/content/modules/creating-your-own-open-source-project/choosing-a-project-idea.mdx
  src/content/modules/creating-your-own-open-source-project/index.mdx
  src/content/modules/getting-started-with-open-source/building-a-portfolio-with-open-source-contributions.mdx
  src/content/modules/getting-started-with-open-source/finding-open-source-projects.mdx
  src/content/modules/getting-started-with-open-source/getting-involved-in-the-open-source-community.mdx
  src/content/modules/getting-started-with-open-source/index.mdx
  src/content/modules/getting-started-with-open-source/overcoming-challenges-in-open-source-contributions.mdx
  src/content/modules/what-is-open-source/brief-history-of-open-source.mdx
  src/content/modules/what-is-open-source/examples-of-successful-open-source-projects.mdx
  src/content/modules/what-is-open-source/index.mdx
Labels: content, bug fix

#78 ci: update showcase
  src/data/showcase.json
Labels: ci

#79 feat: add skip link
  src/components/SkipLink.astro
  src/layouts/Layout.astro
Labels: feature

#77 fix: improve selection colors readability
  src/global.css
Labels: bug fix

#76 chore(deps): bump dependencies
  package-lock.json
  package.json
Labels: dependencies

#84 chore(deps): bump astro from 2.5.3 to 2.5.4
  package-lock.json
  package.json
Labels: dependencies

#86 chore(deps): bump dependencies
  package-lock.json
  package.json
Labels: dependencies

#83 Showcase page improvements
  .github/workflows/weekly.yaml
  package-lock.json
  package.json
  scripts/update-showcase.mjs
  scripts/update-showcase.ts
  src/components/showcase/ShowcaseBanner.astro
  src/components/showcase/ShowcaseEntry.astro
  src/components/showcase/ShowcaseGitHubLink.astro
  src/components/showcase/ShowcaseGitHubRepoLink.astro
  src/components/showcase/ShowcaseGitHubRepoStat.astro
  src/components/showcase/ShowcaseUnknownLink.astro
  src/content/config.ts
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/fabiocaccamo.json
  src/data/showcase.json
  src/pages/index.astro
  src/pages/showcase/index.astro
Labels: feature

#87 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/fabiocaccamo.json
Labels: ci

#88 Showcase improvements follow-up
  .github/workflows/integration.yml
  README.md
  package-lock.json
  package.json
  scripts/libs/showcaseScrapper.ts
  scripts/update-showcase.ts
  tests/showcase.test.ts
Labels: feature

#90 chore(config): add `compressHTML`
  astro.config.mjs
Labels: enhancement, chore

#92 feat(search): change issue creation URL when search without results
  src/layouts/Layout.astro
Labels: feature

#96 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/fabiocaccamo.json
Labels: ci
