Repository Open-reSource/openresource.dev, pull requests merged in 2023-04, with the labels that each got.

#5 feat(chapters): add previous/next buttons
  src/pages/guide/[...slug].astro
  tailwind.config.cjs
Labels: feature

#9 ci: update showcase
  src/data/showcase.json
Labels: ci

#10 ci: update showcase
  src/data/showcase.json
Labels: ci

#13 ci: add npm dependencies caching
  .github/workflows/weekly.yaml
Labels: enhancement, ci

#14 feat(chapters): add creation and last update dates + reading time
  src/content/config.ts
  src/content/modules/creating-your-own-open-source-project/choosing-a-project-idea.mdx
  src/content/modules/creating-your-own-open-source-project/planning-your-project.mdx
  src/content/modules/getting-started-with-open-source/building-a-portfolio-with-open-source-contributions.mdx
  src/content/modules/getting-started-with-open-source/contributing-to-open-source.mdx
  src/content/modules/getting-started-with-open-source/finding-open-source-projects.mdx
  src/content/modules/getting-started-with-open-source/getting-involved-in-the-open-source-community.mdx
  src/content/modules/getting-started-with-open-source/overcoming-challenges-in-open-source-contributions.mdx
  src/content/modules/what-is-open-source/brief-history-of-open-source.mdx
  src/content/modules/what-is-open-source/definition-of-open-source.mdx
  src/content/modules/what-is-open-source/examples-of-successful-open-source-projects.mdx
  src/content/modules/what-is-open-source/importance-of-open-source.mdx
  src/pages/guide/[...slug].astro
Labels: feature

#11 feat(showcase): new /showcase page
  package-lock.json
  package.json
  src/components/Footer.astro
  src/pages/showcase/index.astro
Labels: feature

#18 ci: update showcase
  src/data/showcase.json
Labels: ci

#19 feat: add showcase banner in `/` and `/showcase`
  src/components/ShowcaseBanner.astro
  src/pages/index.astro
  src/pages/showcase/index.astro
Labels: feature

#20 feat(scripts): get GH repo data when showcase link is a repo
  scripts/update-showcase.mjs
Labels: feature

#22 ci: update showcase
  src/data/showcase.json
Labels: ci
