Repository Open-reSource/openresource.dev, pull requests merged in 2024-11, with the labels that each got.

#982 feat(resources): add banners to books and events resources pages
  src/assets/resources/books.png
  src/assets/resources/events.png
  src/content/docs/resources/books.mdx
  src/content/docs/resources/events.mdx
Labels: feature

#986 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/ajayts07.json
  src/content/showcase/anav5704.json
  src/content/showcase/castarco.json
  src/content/showcase/confused-Techie.json
  src/content/showcase/crftwrk.json
  src/content/showcase/diamant3.json
  src/content/showcase/fabiocaccamo.json
  src/content/showcase/gokulkrishh.json
  src/content/showcase/mevdschee.json
  src/content/showcase/nkdas91.json
  src/content/showcase/pranshugupta54.json
  src/content/showcase/pylapp.json
  src/content/showcase/rochacbruno.json
  src/content/showcase/rossrobino.json
  src/content/showcase/sebastiandotdev.json
  src/content/showcase/trobonox.json
Labels: ci

#989 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/ajayts07.json
  src/content/showcase/azat-io.json
  src/content/showcase/confused-Techie.json
  src/content/showcase/crftwrk.json
  src/content/showcase/diamant3.json
  src/content/showcase/fabiocaccamo.json
  src/content/showcase/gokulkrishh.json
  src/content/showcase/mevdschee.json
  src/content/showcase/nkdas91.json
  src/content/showcase/patkon.json
  src/content/showcase/pranshugupta54.json
  src/content/showcase/pylapp.json
  src/content/showcase/rochacbruno.json
  src/content/showcase/rossrobino.json
  src/content/showcase/trobonox.json
Labels: ci

#994 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/ajayts07.json
  src/content/showcase/azat-io.json
  src/content/showcase/castarco.json
  src/content/showcase/confused-Techie.json
  src/content/showcase/crftwrk.json
  src/content/showcase/diamant3.json
  src/content/showcase/fabiocaccamo.json
  src/content/showcase/mevdschee.json
  src/content/showcase/nkdas91.json
  src/content/showcase/nousantx.json
  src/content/showcase/patkon.json
  src/content/showcase/pranshugupta54.json
  src/content/showcase/pylapp.json
  src/content/showcase/rochacbruno.json
  src/content/showcase/trobonox.json
Labels: ci

#1003 ci: update showcase
  src/content/showcase/ArtyomVancyan.json
  src/content/showcase/ajayts07.json
  src/content/showcase/anav5704.json
  src/content/showcase/azat-io.json
  src/content/showcase/castarco.json
  src/content/showcase/confused-Techie.json
  src/content/showcase/crftwrk.json
  src/content/showcase/diamant3.json
  src/content/showcase/fabiocaccamo.json
  src/content/showcase/gokulkrishh.json
  src/content/showcase/mevdschee.json
  src/content/showcase/patkon.json
  src/content/showcase/pranshugupta54.json
  src/content/showcase/pylapp.json
  src/content/showcase/rochacbruno.json
  src/content/showcase/rossrobino.json
  src/content/showcase/trobonox.json
Labels: ci

#1011 ci: update showcase
  src/content/showcase/ajayts07.json
  src/content/showcase/anav5704.json
  src/content/showcase/azat-io.json
  src/content/showcase/confused-Techie.json
  src/content/showcase/crftwrk.json
  src/content/showcase/diamant3.json
  src/content/showcase/fabiocaccamo.json
  src/content/showcase/gokulkrishh.json
  src/content/showcase/mevdschee.json
  src/content/showcase/patkon.json
  src/content/showcase/pranshugupta54.json
  src/content/showcase/pylapp.json
  src/content/showcase/rochacbruno.json
  src/content/showcase/trobonox.json
Labels: ci

#1012 Update books.mdx
  src/content/docs/resources/books.mdx
Labels: enhancement, guide
